version: "3.9"
services:
  backend:
    build:
      context: ./backend
    stdin_open: true
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build:
      context: ./frontend
    environment:
      NODE_ENV: "development"
    command: "npm run start"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/
      - ./frontend/node_modules:/app/node_modules
volumes:
  backend:
  frontend:
  frontend-dev: