version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/
      - ./frontend/node_modules:/app/node_modules
volumes:
  backend:
  frontend: